language: php
before_install:
- openssl aes-256-cbc -K $encrypted_fb4a6b67ec62_key -iv $encrypted_fb4a6b67ec62_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
  # 添加如下两行内容，Host后面的ip替换成你的部署服务器地址
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 106.75.15.41\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - composer install --prefer-dist --optimize-autoloader --quiet
before_script: composer require phpunit/phpunit
script: phpunit tests/Feature/ExampleTest.php
# 添加一个名为after_success的钩子，并写入你需要执行部署操作的命令
after_success:
  - ssh ubuntu@106.75.15.41 "cd /var/www/blog && git pull"
